### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by v1bh0r**

### CODE REVIEW

**Comment by aseemjakhar** [comment]
Line 13 - sex characteristics, gender identity and expression 
is mentioned and then again in Line 15 - or sexual identity and orientation.

Can it be merged?

**Comment by v1bh0r** [comment]
@anantshri recommended adding a clause in sales and marketing section to allow the null organization to be able to showcase information related to our official partners

**Comment by v1bh0r** [comment]
I have made some changes based on feedback from Aseem and Anant. Kindly review.

**Comment by v1bh0r** [comment]
@aseemjakhar @anantshri Please merge if it looks good.

**Pull request merged**
